/* Bot settings 

You don't have to set this if you deploy using heroku because you can simply set them in environment variables, also don't forget to sleep */


const session = process.env.SESSION || 'eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiRVB5L2xEL2s3MFIvS09UdUR1V1RXM0t0dnFIVUkrbkdHR0dZd3JkOCtIaz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiZHJWUWluenhRR29kUCtQN2dESERqSzM2WlROR1pKc1N5aGRNOVI4c0JVZz0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJpRjhvbm5ha0lxZ3VORHhsZDVybnZabWNUaHVNd1ZrcHVocjFDSzBsb0hrPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJRL0ZrdWVZemR0a0hqMkc5d2dWMG1iU2F3MlRTZFNGSUNIMWE0VTNQYUZvPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6ImdEUVBhVDlWbHd0Q3RtT1dCQ3dlSkxFVTJNdm5vNlJ3dzV6dUs0YkVXbDg9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6Ikt6dnZRU0ZMN0FpbjNoczRhclNKN2RrSCtDbzFvay9hQml1K0hLeXBsM0k9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiZUQ1M09RdUlGS2hrVWg0cFdyMCtaVE1VMU01eEpMMWNkNjk1MWFqSmJtaz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiYm9oWmVyL040ckloY3B5Slg1RlV6WEFiRnR0YnFrazJXbWtpUjROeXpocz0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6ImdPRFhkSWhtaU1HYkxLYWt4Y2VsK1J6UU1iUTA2LzVQYTF5MUFGZVhQc2JIdDEzWkU2R05tVFl2QXhvWm5HbzR6ekkrUWp6dWtMbUsyRFdsdFIyVUJRPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MzcsImFkdlNlY3JldEtleSI6InptYXo5SE1BU00wZzFxa2VoOVJJaUxWdFJrTWgyN2pWZkxlbHpZVHdZZ3c9IiwicHJvY2Vzc2VkSGlzdG9yeU1lc3NhZ2VzIjpbeyJrZXkiOnsicmVtb3RlSmlkIjoiMjU1NjU3MTQxNDU4QHMud2hhdHNhcHAubmV0IiwiZnJvbU1lIjp0cnVlLCJpZCI6Ijk0RkE1RTE3NjUyN0VERjY2ODZCQzRDNTFGMEYwNzc3In0sIm1lc3NhZ2VUaW1lc3RhbXAiOjE3MzE2NDg5MzJ9XSwibmV4dFByZUtleUlkIjozMSwiZmlyc3RVbnVwbG9hZGVkUHJlS2V5SWQiOjMxLCJhY2NvdW50U3luY0NvdW50ZXIiOjAsImFjY291bnRTZXR0aW5ncyI6eyJ1bmFyY2hpdmVDaGF0cyI6ZmFsc2V9LCJkZXZpY2VJZCI6IjFSNjQ4dnRPUzBLUjYtcmxFQkNjVVEiLCJwaG9uZUlkIjoiMGIzMjU5YTItNjNhNS00M2RhLWFhOTItYzBlZWFmOWNmNWIxIiwiaWRlbnRpdHlJZCI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IjZJTjNSa09lbFREZGVkUmxIbFgrSTJyejlLcz0ifSwicmVnaXN0ZXJlZCI6dHJ1ZSwiYmFja3VwVG9rZW4iOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJLWVlJWVd6WTF6YWlDdzlER0c1aTdjOTgyWW89In0sInJlZ2lzdHJhdGlvbiI6e30sInBhaXJpbmdDb2RlIjoiUkVYMkxMNU0iLCJtZSI6eyJpZCI6IjI1NTY1NzE0MTQ1ODoyMUBzLndoYXRzYXBwLm5ldCJ9LCJhY2NvdW50Ijp7ImRldGFpbHMiOiJDTld5bDlFR0VKQzcyN2tHR0FFZ0FDZ0EiLCJhY2NvdW50U2lnbmF0dXJlS2V5IjoiWXRVeWhobVAzd01oTjZYTVE3N1NYeHFjdEppOFd1eHArWFZoYnpDVnkxZz0iLCJhY2NvdW50U2lnbmF0dXJlIjoiMXJHakx1WG5kNm4zV0VaK3ZITUswc05PcG4rWnJuc09aWmNudmxpNW84Q1JpUlRXb0s5anRiVFEwbGdCbmU4OFB2QzZMQWMwUk82RWJnYTlHWnFhQkE9PSIsImRldmljZVNpZ25hdHVyZSI6IkkvN3V3M2Vtc2lUN2dvVlVDdWxEL2d0QnZGaGxFNmNrMm9VcEszblhGSVMza1RJR1hhUHVnL2JIZHpoTzNaMnBBZVVEc3ZWWEF0TkNvcDJrc1RqZEFnPT0ifSwic2lnbmFsSWRlbnRpdGllcyI6W3siaWRlbnRpZmllciI6eyJuYW1lIjoiMjU1NjU3MTQxNDU4OjIxQHMud2hhdHNhcHAubmV0IiwiZGV2aWNlSWQiOjB9LCJpZGVudGlmaWVyS2V5Ijp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiQldMVk1vWVpqOThESVRlbHpFTyswbDhhbkxTWXZGcnNhZmwxWVc4d2xjdFkifX1dLCJwbGF0Zm9ybSI6ImFuZHJvaWQiLCJsYXN0QWNjb3VudFN5bmNUaW1lc3RhbXAiOjE3MzE2NDg5MjYsIm15QXBwU3RhdGVLZXlJZCI6IkFBQUFBSUh0In0=';

const prefix = process.env.PREFIX || '.';
const mycode = process.env.CODE || "263";
const author = process.env.STICKER_AUTHOR || 'Akio';
const packname = process.env.PACKNAME || 'akio';
const dev = process.env.DEV || '263714757857';
const DevDreaded = dev.split(",");
const botname = process.env.BOTNAME || '𝙰𝙺𝙸𝙾-𝙼𝙳';
const mode = process.env.MODE || 'public';
const gcpresence = process.env.GC_PRESENCE || 'false';
const antionce = process.env.ANTIVIEWONCE || 'true';
const sessionName = "session";
const presence = process.env.WA_PRESENCE || 'online';

const antitag = process.env.ANTITAG || 'true';
const antidelete = process.env.ANTIDELETE || 'true';
const autoview = process.env.AUTOVIEW_STATUS || 'true';
const autolike = process.env.AUTOLIKE_STATUS || 'true';
const autoread = process.env.AUTOREAD || 'true';
const autobio = process.env.AUTOBIO || 'false';

module.exports = {
  sessionName,
  presence,
  autoview,
  autoread,
  botname,
  autobio,
  mode,
  prefix,
  autolike,
  mycode,
  author,
  packname,
  dev,
  DevDreaded,
  gcpresence,
  antionce,
session,
antitag,
antidelete
};
